CREATE OR ALTER TASK {{ENVIRONMENT}}.LOAD.TASK_EXCHANGE_RATE_REFRESH_DLY
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 09 * * * AMERICA/LOS_ANGELES'
AS
INSERT OVERWRITE INTO {{ENVIRONMENT}}.LOAD.STG_EXCHANGE_RATE
SELECT * FROM FINANCE__ECONOMICS.CYBERSYN.FX_RATES_TIMESERIES WHERE QUOTE_CURRENCY_ID='INR' ORDER BY DATE DESC LIMIT 1;